import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const html = readFileSync(new URL('../src/index.html', import.meta.url), 'utf8');
const js = readFileSync(new URL('../src/main.js', import.meta.url), 'utf8');
const css = readFileSync(new URL('../src/styles.css', import.meta.url), 'utf8');

assert.match(html, /id="micButton"/);
assert.match(html, /id="audioInputSelect"/);
assert.match(html, /id="audioInputStatus"/);
assert.match(html, /id="bubblePage"/);
assert.match(html, /<button id="bubble"[^>]*aria-label="吹き出しを閉じる"[^>]*title="クリックで閉じる"/);
assert.match(html, /class="thinking-dots"/);
assert.match(html, /id="restoreControlsButton"/);
assert.match(html, /id="voiceButton"/);
assert.match(html, /id="microphoneMuteButton"[^>]*aria-pressed="false"/);
assert.match(html, /id="characterSettingsButton"/);
assert.match(html, /id="newConversationButton"/);
assert.match(html, /id="characterDialog"/);
assert.doesNotMatch(html, /id="characterLocalLlmMode"/);
assert.match(html, /id="characterConversationLog"/);
assert.match(html, /id="notionParentPage"/);
assert.match(html, /id="notionLoggingToggle"/);
assert.match(html, /id="saveNotionSettingsButton"/);
assert.match(html, /id="characterAgent"/);
assert.doesNotMatch(html, /id="(?:characterName|characterRole|characterBackend|characterModel|characterInstruction|guideDialog)"/);
assert.match(html, /avatar-closed\.png/);
assert.match(html, /avatar-open\.png/);
assert.match(js, /\/api\/avatar\/message/);
assert.match(js, /new EventSource\('\/api\/avatar\/events'\)/);
assert.match(js, /new EventSource\('\/api\/avatar\/overlay\/events'\)/);
assert.match(js, /fetch\('\/api\/avatar\/overlay\/state'/);
assert.match(js, /navigator\.sendBeacon\('\/api\/avatar\/overlay\/state'/);
assert.match(js, /!activeThreadId \|\| event\.thread_id !== activeThreadId/);
assert.match(js, /window\.speechSynthesis\?\.cancel\?\.\(\)/);
assert.match(js, /window\.speechSynthesis\.resume\(\)/);
assert.match(js, /speechSynthesis\?\.getVoices\?\.\(\)/);
assert.match(js, /elements\.voice\.addEventListener\('click', testVoice\)/);
assert.match(js, /new ServerAudioPlayback\(\)/);
assert.match(js, /serverAudioPlayback\.unlock\(\)/);
assert.match(js, /serverAudioPlayback\.play\(blob/);
assert.match(js, /xangi-avatar:custom-characters/);
assert.match(js, /config\.characterSettings/);
assert.match(js, /\/api\/avatar\/settings\/characters/);
assert.match(js, /await saveCharacterSettings\(nextCharacters, character\.id\)/);
assert.match(js, /import bundledAvatarClosed from '\.\/assets\/avatar-closed\.png'/);
assert.match(js, /resolveCharacterImage/);
assert.match(js, /\/api\/avatar\/workspace-image/);
assert.match(js, /new URLSearchParams\(\{ agentId, path: value \}\)/);
assert.match(js, /fetch\('\/api\/avatar\/session'/);
assert.match(js, /\/api\/avatar\/session\/close/);
assert.match(js, /\/api\/avatar\/session\/status/);
assert.match(js, /replaceAvatarSession\('screen'\)/);
assert.match(js, /loadCharacterSession\(localStorage, `\$\{mode\}:\$\{activeCharacter\(\)\.agentId/);
assert.match(js, /config\.agents/);
assert.match(js, /!\('SpeechSynthesisUtterance' in window\)[\s\S]*setState\('idle'\)/);
assert.match(js, /window\.SpeechRecognition \|\| window\.webkitSpeechRecognition/);
assert.match(js, /openAudioInput\(navigator\.mediaDevices, selectedAudioInputId\)/);
assert.match(js, /splitBubblePages\(nextText, bubblePageLimit\(\)\)/);
assert.match(js, /assessTranscript\(result\)/);
assert.match(js, /onCalibrating:/);
assert.match(js, /activeAudioInputLabel/);
assert.match(js, /classList\.toggle\('is-thinking'/);
assert.match(js, /new ScreenConversation/);
assert.match(js, /\/api\/avatar\/frame/);
assert.match(html, /画面共有を開始/);
assert.doesNotMatch(html, /youtube|accounts\.google\.com\/gsi\/client/i);
assert.doesNotMatch(js, /youtube|\/api\/avatar\/settings\/youtube/i);
assert.match(js, /const framePromise = screenConversation\.active \? screenConversation\.capture\(\)/);
assert.match(js, /buildScreenConversationPrompt\(text, upload\.imagePath\)/);
assert.match(js, /sendUserMessage\(text\)/);
assert.match(js, /sendUserMessage\(assessment\.text/);
assert.match(js, /handsFree\.setMuted\(microphoneMuted\)/);
assert.doesNotMatch(js, /screenConversation\.start\(\)\.then\(\(\) => handsFree\.start\(\)\)/);
assert.doesNotMatch(js, /handsFreeButton'\)\.disabled = active/);
assert.doesNotMatch(js, /localLlmHistoryTurns|localLlmCurrentImageOnly/);
assert.match(js, /\/api\/avatar\/conversation-log/);
assert.match(js, /\/api\/avatar\/settings\/notion/);
assert.match(js, /xangi-avatar:notion-logging/);
assert.match(js, /const source = editingCharacter \|\| activeCharacter\(\)/);
assert.doesNotMatch(js, /presetWorkspaceIds|characterWorkspace/);
assert.doesNotMatch(html, /id="characterWorkspace"/);
assert.match(js, /function dismissBubble\(\)/);
assert.match(js, /elements\.bubble\.addEventListener\('click', dismissBubble\)/);
assert.match(js, /if \(overlayView && receivedOverlayState\)/);
assert.match(js, /visualTurnRecords/);
assert.doesNotMatch(js, /screenConversation\.queueNext\(\)/);
assert.match(js, /\/api\/avatar\/stt/);
assert.match(js, /\/api\/avatar\/tts/);
assert.match(js, /mode = findCharacter\(elements\.mode\.value\)\.id/);
assert.match(js, /customCharacters\.find\(\(\{ id \}\) => id === requestedMode\)/);
assert.doesNotMatch(html, /Whisper（準備中）|サーバーTTS（準備中）|Local LLM（準備中）/);
assert.match(html, /xangiの会話設定/);
assert.match(html, /<legend>音声設定<\/legend>/);
assert.doesNotMatch(html, /id="characterImage(?:Closed|Open)" type="url"/);
assert.match(html, /ワークスペース相対パス/);
assert.match(js, /params\.get\('controls'\) === '1'/);
assert.match(js, /\['overlay', 'character', 'bubble'\]\.includes\(view\)/);
assert.match(js, /elements\.restoreControls\.addEventListener/);
assert.match(css, /data-background="green"/);
assert.match(css, /data-controls="hidden"/);
assert.match(css, /data-view="app"\]\[data-controls="hidden"\] \.restore-controls/);
assert.match(css, /data-view="overlay"\] \.restore-controls/);
assert.match(css, /data-view="character"\] \.speech-bubble/);
assert.match(css, /data-view="bubble"\] \.avatar/);
assert.match(css, /data-view="bubble"\] \.speech-bubble \{[^}]*bottom: auto;[^}]*height: auto;[^}]*border-radius: 24px;/);
assert.match(css, /data-view="bubble"\] \.speech-bubble::after \{[^}]*display: none;/);
assert.match(css, /mouth-flap/);
assert.match(css, /thinking-dot/);
assert.match(css, /\.speech-bubble #bubbleText \{[^}]*overflow: hidden/);
assert.match(css, /\.speech-bubble \{[^}]*cursor: pointer;[^}]*touch-action: manipulation;/);
assert.doesNotMatch(css, /\.speech-bubble[^\n]*overflow:\s*(?:auto|scroll)/);

console.log('web app contract tests passed');
